apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer # This ensures that the storage is provisioned in the right AZ
